### ISSUE TITLE
Mutation startChat add logged user twice

### ISSUE THREAD

**Issue by northersky** [alex996/graphql-chat#8]
resolvers/chat.js

The logged user is added twice

```
if (idsFound !== userIds.length) {
        throw new UserInputError('One or more User IDs are invalid.')
      }

      const chat = await Chat.create({ title, users: userIds })
```
Change to:

```
if (idsFound !== userIds.length) {
        throw new UserInputError('One or more User IDs are invalid.')
      }

      if (!userIds.filter(u => u.id === userId)) {
        userIds.push(userId)
      }

      const chat = await Chat.create({ title, users: userIds })
```

**Comment by alex996** [comment]
It's not. `startChat` joi schema clearly says [`.not(userId)`](https://github.com/alex996/graphql-chat/blob/42f3bd3ab975f5ba503c08b4c6fef9444c275e2d/src/schemas/chat.js#L6). `userId` may or may not be there; if it is, you have to make sure that there's at least one ID for a user other than yourself. Again, as I mentioned in #7, it complicates validation, so I explicitly reject `userId` upfront, and only push it to the array myself. If you start a chat, you're already part of it, because you're the initiator; you don't need to add yourself explicitly.
