### ISSUE TITLE
Will you still post videos on your YouTube channel?

### ISSUE THREAD

**Issue by greguintow** [alex996/graphql-chat#9]
I just would like to know if you are going to continue your YT Series of this repository, because I realized that you are updating the repository but not the videos

**Comment by alex996** [comment]
Yes sir. I made the mistake of not finishing the project and filming it impromptu. For an app of this scope, it needs to be thought out in advance. Otherwise, I would just make a fool out of myself with silly typos and changing direction of the videos. I more or less figured out how I want to build it. Now the plan is to finish it, then share what I've done on YT.
